SCENARIOS = {
    "coffee_shop": {
        "id": "coffee_shop",
        "title": "Café Order",
        "character": "Sofia",
        "character_role": "barista",
        "setting": "A busy café in the city center",
        "goal": "Order a coffee and pastry, ask for the wifi password",
        "vocabulary_targets": ["coffee", "order", "please", "thank you", "how much", "wifi", "milk", "sugar"],
        "turns_to_complete": 8,
    },
    "job_interview": {
        "id": "job_interview",
        "title": "Job Interview",
        "character": "Marco",
        "character_role": "HR manager",
        "setting": "A modern office meeting room",
        "goal": "Introduce yourself, describe your experience, and ask about the role",
        "vocabulary_targets": ["experience", "skills", "team", "project", "opportunity", "motivated", "background", "position"],
        "turns_to_complete": 8,
    },
    "medical_consultation": {
        "id": "medical_consultation",
        "title": "Doctor's Appointment",
        "character": "Dr. Chen",
        "character_role": "general practitioner",
        "setting": "A doctor's consultation room",
        "goal": "Describe your symptoms to the doctor and understand the diagnosis and treatment",
        "vocabulary_targets": ["pain", "symptom", "fever", "headache", "medication", "diagnosis", "treatment", "prescription", "allergy"],
        "turns_to_complete": 8,
    },
    "clothing_store": {
        "id": "clothing_store",
        "title": "Shopping for Clothes",
        "character": "Marie",
        "character_role": "store employee",
        "setting": "A small boutique that sells accessories, clothes, and small gifts",
        "goal": "Ask for help finding an outfit for a specific occasion, inquire about sizes and colors, and complete a purchase.",
        "vocabulary_targets": ["clothes", "buy", "please", "price", "how much", "event", "party", "gift", "thank you"],
        "turns_to_complete": 8,
    },
     "hotel_check_in": {
        "id": "hotel_check_in",
        "title": "Hotel Check-In",
        "character": "Juan",
        "character_role": "front desk worker",
        "setting": "The lobby and front desk of a nice hotel",
        "goal": "Check into your reserved room, ask about hotel amenities, and request information about local attractions or facilities, and restaurant recommendations.",
        "vocabulary_targets": ["room", "stay", "food", "activities", "restaurants", "local", "ameneties", "thank you"],
        "turns_to_complete": 8,
    },
    "grocery_store": {
        "id": "grocery_store",
        "title": "Grocery Shopping",
        "character": "Lucas",
        "character_role": "store employee",
        "setting": "A busy supermarket",
        "goal": "Find items on your shopping list, ask where things are located, ask for local recommendations, and check out at the register.",
        "vocabulary_targets": ["aisle", "fresh", "organic", "price", "discount", "bag", "cash", "card", "receipt", "where is"],
        "turns_to_complete": 8,
    },
    "airport": {
        "id": "airport",
        "title": "Airport Check-In",
        "character": "Annie",
        "character_role": "airline check-in agent",
        "setting": "A busy international airport departure terminal",
        "goal": "Check in for your flight, ask about baggage and any fees, and find out which gate to go to.",
        "vocabulary_targets": ["passport", "ID", "plane", "flight","boarding pass", "luggage", "gate", "departure", "seat", "window", "delay", "carry-on"],
        "turns_to_complete": 8,
    },
    "restaurant": {
        "id": "restaurant",
        "title": "Restaurant Dinner",
        "character": "Jack",
        "character_role": "waiter",
        "setting": "A mid-range, nice sit-down restaurant",
        "goal": "Make a reservation or ask to be seated, ask for dish recommendations, order food and drinks, pay handle the bill.",
        "vocabulary_targets": ["menu", "recommend", "allergic", "vegetarian", "well-done", "appetizer", "dessert", "bill", "tip"],
        "turns_to_complete": 10,
    },
    "subway": {
        "id": "subway",
        "title": "Navigating a Subway/Metro Station",
        "character": "Kenji",
        "character_role": "transit worker",
        "setting": "A subway station in a large city",
        "goal": "Buy a metro ticket, ask for directions to your destination, and confirm you are on the right train.",
        "vocabulary_targets": ["ticket", "line", "transfer", "platform", "direction", "exit", "stop", "map", "fare"],
        "turns_to_complete": 8,
    },
}
